outfits = [
    ('ОБОРОТЕНЬ', 'stickers/warewolf.webp'),
    ('СКЕЛЕТ', 'stickers/sceleton.tgs'),
    ('ВАМПИР', 'stickers/vampire.tgs'),
    ('ВЕДЬМА', 'stickers/witch.webp'),
    ('ПЕННИВАЙЗ', 'stickers/pennywise.webp'),
    ('ФРАНКЕНШТЕЙН', 'stickers/frankenstein.webp'),
    ('ВСАДНИК БЕЗ ГОЛОВЫ', 'stickers/headless.webp'),
    ('ФРЕДДИ КРЮГЕР', 'stickers/krueger.webp'),
    ('ЖИВОЙ МЕРТВЕЦ', 'stickers/undead.tgs'),
    ('ЧУЖОЙ', 'stickers/alien.webp'),
    ('КРИПЕР', 'stickers/creeper.webp'),
    ('ПРИВЕДЕНИЕ', 'stickers/ghost.tgs'),
    ('ФАРАОН', 'stickers/pharaoh.webp'),
    ('СМЕРТЬ С КОСОЙ', 'stickers/grimreaper.tgs'),
    ('ЧУМНОЙ ДОКТОР', 'stickers/plaguedoctor.tgs'),
    ('КРИК', 'stickers/scream.webp'),
    ('ТАНОС', 'stickers/thanos.webp'),
    ('ДЖЕЙСОН ВУРХИС', 'stickers/jason.webp'),
    ('АННАБЕЛЬ', 'stickers/annabel.webp'),
    ('ЖЕНЩИНА КОШКА', 'stickers/catwoman.webp'),
    ('ДЕДПУЛ', 'stickers/deadpool.webp'),
    ('ДЕМОНИЦА', 'stickers/demon.webp'),
    ('ХАРЛИ КВИНН', 'stickers/harley.webp'),
    ('РОБОТ УБИЙЦА', 'stickers/killerobot.webp'),
    ('ЛЕДИ ДЕДПУЛ', 'stickers/ladydeadpool.webp'),
    ('ОУШЕНМЕН', 'stickers/oceanman.webp'),
    ('МЕДУЗА', 'stickers/medusa.webp'),
    ('СЛЕНДЕР', 'stickers/slender.webp'),
    ('МУМИЯ', 'stickers/mummy.webp'),
    ('ЧЕЛОВЕК МУХА', 'stickers/flyman.webp'),
    ('МОНАХИНЯ', 'stickers/nun.webp'),
    ('ТРАМП', 'stickers/trump.tgs'),
    ('ДЖЕК СКЕЛИНГТОН', 'stickers/jack.tgs'),
    ('ДЖОКЕР', 'stickers/joker.tgs'),
    ('ГАННИБАЛ ЛЕКТОР', 'stickers/hanibal.tgs'),
    ('КУКЛА БИЛЛИ', 'stickers/saw.tgs')
]